import type { Language } from "@/i18n/translations";

/**
 * SINGLE SOURCE OF TRUTH for /hotel (Siam Hotel & Hostel, Sairee Beach, Koh Tao).
 *
 * Everything the page renders - room list, prices, amenities, every string in
 * all four languages - lives here. The components read it and render; they hold
 * no copy of their own. That is deliberate: prices and room facts arrive from
 * Ben separately from the build, and a price change must never require touching
 * a component.
 *
 * REAL INVENTORY (2026-08-17): the 12 rooms below are Ben's confirmed room
 * list with real THB prices and per-room photo sets (generated by
 * scripts/build-hotel-images.sh from his per-room folders). Check-in /
 * check-out times confirmed by reception 2026-08-18 (14:00 / 11:00).
 */

// ---------------------------------------------------------------------------
// Property info
// ---------------------------------------------------------------------------

/**
 * The hotel shares the dive shop's WhatsApp line. If the property gets its own
 * number, changing it here changes every Book button on the page.
 *
 * WHATSAPP-ONLY (Ben, 2026-08-17): this number takes no voice calls. Never
 * render it as a tel: link anywhere on the hotel page - wa.me links only.
 *
 * NOTE: the prefilled messages below carry NO [ref:CODE] tag on purpose. Nemo's
 * n8n classifier routes on that tag and has no hotel branch yet, so an invented
 * code would land in a dead route; untagged messages fall through to the AI
 * bucket, which is the correct behaviour until a HOTEL node exists.
 */
export const HOTEL_WHATSAPP_NUMBER = "66825068898";

export const HOTEL_INFO = {
  name: "Siam Hotel & Hostel",
  address: "9/9 Moo 1, Sairee Beach, Koh Tao, Surat Thani 84360, Thailand" as string | null,
  area: "Sairee Beach, Koh Tao",
  /** Confirmed by reception via Ben, 2026-08-18. */
  checkIn: "14:00" as string | null,
  checkOut: "11:00" as string | null,
  mapsUrl: "https://maps.app.goo.gl/bzHAbVgMkBvaMCTF7" as string | null,
  instagram: null as string | null,
} as const;

// ---------------------------------------------------------------------------
// Rooms
// ---------------------------------------------------------------------------

export type AmenityKey =
  | "ac"
  | "fan"
  | "hotWater"
  | "ensuite"
  | "tv"
  | "safe"
  | "fridge"
  | "kettle"
  | "wifi"
  | "poolAccess"
  | "doubleBed"
  | "doubleOrTwin"
  | "bunkBeds"
  | "lockers"
  | "wardrobe"
  | "desk"
  | "terrace"
  | "seatingArea"
  | "seaView"
  | "poolView"
  | "gardenView"
  | "streetSide";

export interface HotelRoom {
  slug: string;
  /** Display order, cheapest first. Prices now sort the list; this breaks ties. */
  order: number;
  /** Image basenames in /public/hotel (no extension). Empty = placeholder card. */
  images: string[];
  sleeps: number | null;
  /** Display order matters: distinctive chips (beds, views, terrace) first. */
  amenities: AmenityKey[];
  /** THB per night. null renders as "price on request". */
  pricePerNight: number | null;
  /** "bed" renders the dorm's per-bed price label instead of per-night-per-room. */
  priceUnit?: "bed";
  /**
   * Under renovation (Ben, 2026-08-18): the room stays visible but shows a
   * "fully booked" badge instead of a Book button, so guests don't inquire.
   * Delete the flag when the room reopens.
   */
  soldOut?: true;
  name: Record<Language, string>;
  blurb: Record<Language, string>;
}

export const HOTEL_ROOMS: HotelRoom[] = [
  {
    // 6 bunk beds. Price is PER BED - hence priceUnit.
    slug: "divers-dorm",
    order: 1,
    images: [
      "siam-hotel-koh-tao-divers-dorm",
      "siam-hotel-koh-tao-divers-dorm-2",
      "siam-hotel-koh-tao-divers-dorm-3",
      "siam-hotel-koh-tao-divers-dorm-4",
    ],
    sleeps: null,
    amenities: ["bunkBeds", "lockers", "terrace", "seatingArea", "streetSide", "ac", "fan", "hotWater", "wifi", "poolAccess"],
    pricePerNight: 500,
    priceUnit: "bed",
    name: {
      en: "Divers Dorm",
      he: "דורם צוללים",
      es: "Dorm de Buceadores",
      fr: "Dortoir Plongeurs",
    },
    blurb: {
      en: "A bed in our air-conditioned dorm: six bunk beds, lockers, hot showers and a terrace with outdoor seating on the main street. Pool access included.",
      he: "מיטה בחדר משותף ממוזג: שש מיטות קומתיים, לוקרים, מים חמים ומרפסת עם פינת ישיבה אל הרחוב הראשי. הגישה לבריכה כלולה.",
      es: "Una cama en nuestro dormitorio con aire acondicionado: seis literas, taquillas, agua caliente y una terraza con zona de estar hacia la calle principal. Acceso a la piscina incluido.",
      fr: "Un lit dans notre dortoir climatisé : six lits superposés, casiers, eau chaude et une terrasse avec coin salon sur la rue principale. Accès à la piscine inclus.",
    },
  },
  {
    // 2 units.
    slug: "divers-private",
    order: 2,
    images: [
      "siam-hotel-koh-tao-divers-private",
      "siam-hotel-koh-tao-divers-private-2",
      "siam-hotel-koh-tao-divers-private-3",
      "siam-hotel-koh-tao-divers-private-4",
      "siam-hotel-koh-tao-divers-private-5",
    ],
    sleeps: 2,
    amenities: ["doubleBed", "ac", "fan", "hotWater", "ensuite", "wardrobe", "wifi", "poolAccess"],
    pricePerNight: 1000,
    name: {
      en: "Divers Private",
      he: "חדר צוללים פרטי",
      es: "Habitación Privada para Buceadores",
      fr: "Chambre Privée Plongeurs",
    },
    blurb: {
      en: "A no-frills private double for divers on a budget: air conditioning, hot water, private bathroom and a wardrobe. Sleep well, dive early.",
      he: "חדר זוגי פרטי ובסיסי לצוללים בתקציב: מיזוג, מים חמים, מקלחת פרטית וארון. ישנים טוב, צוללים מוקדם.",
      es: "Una habitación doble privada y sin lujos para buceadores con presupuesto: aire acondicionado, agua caliente, baño privado y armario. Duerme bien, bucea temprano.",
      fr: "Une chambre double privée toute simple pour plongeurs à petit budget : climatisation, eau chaude, salle de bain privée et armoire. Bien dormir, plonger tôt.",
    },
  },
  {
    // 6 units.
    slug: "mermaid-room",
    order: 3,
    images: [
      "siam-hotel-koh-tao-mermaid-room",
      "siam-hotel-koh-tao-mermaid-room-2",
      "siam-hotel-koh-tao-mermaid-room-3",
      "siam-hotel-koh-tao-mermaid-room-4",
      "siam-hotel-koh-tao-mermaid-room-5",
      "siam-hotel-koh-tao-mermaid-room-6",
    ],
    sleeps: 2,
    amenities: ["doubleOrTwin", "seatingArea", "streetSide", "ac", "fan", "hotWater", "ensuite", "fridge", "kettle", "safe", "desk", "wifi", "poolAccess"],
    pricePerNight: 1380,
    name: {
      en: "Mermaid Room",
      he: "חדר מרמייד",
      es: "Habitación Mermaid",
      fr: "Chambre Mermaid",
    },
    blurb: {
      en: "A simple double or twin room on the main street side with outdoor seating - and more inside than the price suggests: fridge, kettle, safe and desk.",
      he: "חדר פשוט עם מיטה זוגית או שתי מיטות בצד הרחוב הראשי ופינת ישיבה חיצונית - ובפנים יותר ממה שהמחיר מרמז: מקרר, קומקום, כספת ושולחן.",
      es: "Una habitación sencilla, doble o con dos camas, del lado de la calle principal y con zona de estar exterior; dentro, más de lo que sugiere el precio: nevera, hervidor, caja fuerte y escritorio.",
      fr: "Une chambre simple, double ou à lits jumeaux, côté rue principale avec coin salon extérieur - et plus d'équipements que le prix ne le laisse penser : réfrigérateur, bouilloire, coffre-fort et bureau.",
    },
  },
  {
    // 8 units.
    slug: "premium-room",
    order: 4,
    images: [
      "siam-hotel-koh-tao-premium-room",
      "siam-hotel-koh-tao-premium-room-2",
      "siam-hotel-koh-tao-premium-room-3",
      "siam-hotel-koh-tao-premium-room-4",
      "siam-hotel-koh-tao-premium-room-5",
      "siam-hotel-koh-tao-premium-room-6",
      "siam-hotel-koh-tao-premium-room-7",
      "siam-hotel-koh-tao-premium-room-8",
    ],
    sleeps: 2,
    amenities: ["doubleOrTwin", "terrace", "streetSide", "ac", "fan", "hotWater", "ensuite", "kettle", "wardrobe", "wifi", "poolAccess"],
    pricePerNight: 1650,
    name: {
      en: "Premium Room",
      he: "חדר פרימיום",
      es: "Habitación Premium",
      fr: "Chambre Premium",
    },
    blurb: {
      en: "Double or twin beds, a terrace on the main street side, and the essentials done well - air conditioning, hot water, kettle and wardrobe.",
      he: "מיטה זוגית או שתי מיטות, מרפסת בצד הרחוב הראשי, וכל מה שצריך - מיזוג, מים חמים, קומקום וארון.",
      es: "Cama doble o dos camas, terraza del lado de la calle principal y lo esencial bien hecho: aire acondicionado, agua caliente, hervidor y armario.",
      fr: "Lit double ou lits jumeaux, une terrasse côté rue principale et l'essentiel bien fait : climatisation, eau chaude, bouilloire et armoire.",
    },
  },
  {
    // 5 units.
    slug: "superior-room",
    order: 5,
    images: [
      "siam-hotel-koh-tao-superior-room",
      "siam-hotel-koh-tao-superior-room-2",
      "siam-hotel-koh-tao-superior-room-3",
      "siam-hotel-koh-tao-superior-room-4",
      "siam-hotel-koh-tao-superior-room-5",
    ],
    sleeps: 2,
    amenities: ["doubleBed", "terrace", "seatingArea", "streetSide", "ac", "fan", "hotWater", "ensuite", "fridge", "wifi", "poolAccess"],
    pricePerNight: 1820,
    soldOut: true,
    name: {
      en: "Superior Room",
      he: "חדר סופיריור",
      es: "Habitación Superior",
      fr: "Chambre Supérieure",
    },
    blurb: {
      en: "A double room on the main street side, with a terrace and outdoor seating. Fridge, air conditioning and a private bathroom.",
      he: "חדר זוגי בצד הרחוב הראשי, עם מרפסת ופינת ישיבה חיצונית. מקרר, מיזוג ומקלחת פרטית.",
      es: "Una habitación doble del lado de la calle principal, con terraza y zona de estar exterior. Nevera, aire acondicionado y baño privado.",
      fr: "Une chambre double côté rue principale, avec terrasse et coin salon extérieur. Réfrigérateur, climatisation et salle de bain privée.",
    },
  },
  {
    // 10+ units.
    slug: "deluxe-room",
    order: 6,
    images: [
      "siam-hotel-koh-tao-deluxe-room",
      "siam-hotel-koh-tao-deluxe-room-2",
      "siam-hotel-koh-tao-deluxe-room-3",
      "siam-hotel-koh-tao-deluxe-room-4",
      "siam-hotel-koh-tao-deluxe-room-5",
      "siam-hotel-koh-tao-deluxe-room-6",
    ],
    sleeps: 2,
    amenities: ["doubleOrTwin", "seaView", "ac", "fan", "hotWater", "ensuite", "kettle", "wardrobe", "wifi", "poolAccess"],
    pricePerNight: 2200,
    soldOut: true,
    name: {
      en: "Deluxe Room",
      he: "חדר דלוקס",
      es: "Habitación Deluxe",
      fr: "Chambre Deluxe",
    },
    blurb: {
      en: "A spacious room with a sea view, double or twin beds and warm teak tones, with a kettle and wardrobe inside.",
      he: "חדר מרווח עם נוף לים, מיטה זוגית או שתי מיטות וגווני טיק חמים, עם קומקום וארון בגדים בפנים.",
      es: "Una habitación amplia con vista al mar, cama doble o dos camas y cálidos tonos de teca, con hervidor y armario.",
      fr: "Une chambre spacieuse avec vue sur la mer, lit double ou lits jumeaux et de chauds tons de teck, avec bouilloire et armoire.",
    },
  },
  {
    // 4 units. Two shoots of the same units ("Bungalow garden" + "Bungalow garden 2"), one room entry.
    slug: "garden-bungalow",
    order: 7,
    images: [
      "siam-hotel-koh-tao-garden-bungalow",
      "siam-hotel-koh-tao-garden-bungalow-2",
      "siam-hotel-koh-tao-garden-bungalow-3",
      "siam-hotel-koh-tao-garden-bungalow-4",
      "siam-hotel-koh-tao-garden-bungalow-5",
      "siam-hotel-koh-tao-garden-bungalow-6",
    ],
    sleeps: 2,
    amenities: ["doubleOrTwin", "poolView", "terrace", "seatingArea", "ac", "fan", "hotWater", "ensuite", "wifi", "poolAccess"],
    pricePerNight: 2370,
    name: {
      en: "Garden Bungalow",
      he: "בקתת גן",
      es: "Bungalow Jardín",
      fr: "Bungalow Jardin",
    },
    blurb: {
      en: "Your own bungalow in the heart of Sairee, with a terrace and outdoor seating facing the pool. Double or twin beds, air conditioning and a private bathroom.",
      he: "בקתה משלכם בלב סיירי, עם מרפסת ופינת ישיבה חיצונית מול הבריכה. מיטה זוגית או שתי מיטות, מיזוג ומקלחת פרטית.",
      es: "Tu propio bungalow en el corazón de Sairee, con terraza y zona de estar exterior frente a la piscina. Cama doble o dos camas, aire acondicionado y baño privado.",
      fr: "Votre bungalow au cœur de Sairee, avec terrasse et coin salon extérieur face à la piscine. Lit double ou lits jumeaux, climatisation et salle de bain privée.",
    },
  },
  {
    // 3 units.
    slug: "suite-sea-view",
    order: 8,
    images: [
      "siam-hotel-koh-tao-suite-sea-view",
      "siam-hotel-koh-tao-suite-sea-view-2",
      "siam-hotel-koh-tao-suite-sea-view-3",
      "siam-hotel-koh-tao-suite-sea-view-4",
      "siam-hotel-koh-tao-suite-sea-view-5",
      "siam-hotel-koh-tao-suite-sea-view-6",
      "siam-hotel-koh-tao-suite-sea-view-7",
    ],
    sleeps: 2,
    amenities: ["doubleOrTwin", "seaView", "poolView", "ac", "fan", "hotWater", "ensuite", "wardrobe", "wifi", "poolAccess"],
    pricePerNight: 2480,
    name: {
      en: "Suite Sea View Room",
      he: "סוויטה עם נוף לים",
      es: "Suite Vista al Mar",
      fr: "Suite Vue Mer",
    },
    blurb: {
      en: "A suite looking out over the sea and the pool, with double or twin beds, a marble bathroom and a wardrobe.",
      he: "סוויטה המשקיפה אל הים והבריכה, עם מיטה זוגית או שתי מיטות, חדר רחצה משיש וארון בגדים.",
      es: "Una suite con vistas al mar y a la piscina, con cama doble o dos camas, baño de mármol y armario.",
      fr: "Une suite donnant sur la mer et la piscine, avec lit double ou lits jumeaux, salle de bain en marbre et armoire.",
    },
  },
  {
    // 3 units.
    slug: "bungalow-suite",
    order: 9,
    images: [
      "siam-hotel-koh-tao-bungalow-suite",
      "siam-hotel-koh-tao-bungalow-suite-2",
      "siam-hotel-koh-tao-bungalow-suite-3",
      "siam-hotel-koh-tao-bungalow-suite-4",
      "siam-hotel-koh-tao-bungalow-suite-5",
      "siam-hotel-koh-tao-bungalow-suite-6",
      "siam-hotel-koh-tao-bungalow-suite-7",
      "siam-hotel-koh-tao-bungalow-suite-8",
    ],
    sleeps: 2,
    amenities: ["doubleOrTwin", "gardenView", "poolView", "terrace", "seatingArea", "ac", "fan", "hotWater", "ensuite", "desk", "wifi", "poolAccess"],
    pricePerNight: 2640,
    name: {
      en: "Bungalow Suite",
      he: "סוויטת בקתה",
      es: "Suite Bungalow",
      fr: "Suite Bungalow",
    },
    blurb: {
      en: "A teak-wood bungalow with canopy beds, a Thai seating corner and a desk, looking over the garden and pool from its own terrace.",
      he: "בקתת עץ טיק עם מיטות אפיריון, פינת ישיבה תאילנדית ושולחן עבודה, משקיפה אל הגינה והבריכה ממרפסת פרטית.",
      es: "Un bungalow de madera de teca con camas con dosel, rincón de estar tailandés y escritorio, con vistas al jardín y la piscina desde su propia terraza.",
      fr: "Un bungalow en teck avec lits à baldaquin, coin salon thaï et bureau, donnant sur le jardin et la piscine depuis sa propre terrasse.",
    },
  },
  {
    // 3 units.
    slug: "triple-room",
    order: 10,
    images: [
      "siam-hotel-koh-tao-triple-room",
      "siam-hotel-koh-tao-triple-room-2",
      "siam-hotel-koh-tao-triple-room-3",
      "siam-hotel-koh-tao-triple-room-4",
      "siam-hotel-koh-tao-triple-room-5",
    ],
    sleeps: 3,
    amenities: ["doubleOrTwin", "seaView", "poolView", "seatingArea", "ac", "fan", "hotWater", "ensuite", "fridge", "kettle", "tv", "safe", "wardrobe", "desk", "wifi", "poolAccess"],
    pricePerNight: 3000,
    soldOut: true,
    name: {
      en: "Triple Room",
      he: "חדר לשלושה",
      es: "Habitación Triple",
      fr: "Chambre Triple",
    },
    blurb: {
      en: "Double or twin beds plus an extra single - room for three, with sea and pool views and outdoor seating. TV, safe, fridge and kettle inside.",
      he: "מיטה זוגית או שתי מיטות ועוד מיטת יחיד - מקום לשלושה, עם נוף לים ולבריכה ופינת ישיבה חיצונית. טלוויזיה, כספת, מקרר וקומקום בפנים.",
      es: "Cama doble o dos camas más una individual extra: espacio para tres, con vistas al mar y a la piscina y zona de estar exterior. TV, caja fuerte, nevera y hervidor.",
      fr: "Lit double ou lits jumeaux plus un lit simple - de la place pour trois, avec vue mer et piscine et coin salon extérieur. TV, coffre-fort, réfrigérateur et bouilloire.",
    },
  },
  {
    // 2 units.
    slug: "sea-front-bungalow",
    order: 11,
    images: [
      "siam-hotel-koh-tao-sea-front-bungalow",
      "siam-hotel-koh-tao-sea-front-bungalow-2",
      "siam-hotel-koh-tao-sea-front-bungalow-3",
      "siam-hotel-koh-tao-sea-front-bungalow-4",
      "siam-hotel-koh-tao-sea-front-bungalow-5",
      "siam-hotel-koh-tao-sea-front-bungalow-6",
      "siam-hotel-koh-tao-sea-front-bungalow-7",
      "siam-hotel-koh-tao-sea-front-bungalow-8",
    ],
    sleeps: 2,
    amenities: ["doubleBed", "seaView", "gardenView", "poolView", "terrace", "seatingArea", "ac", "fan", "hotWater", "ensuite", "fridge", "desk", "wardrobe", "wifi", "poolAccess"],
    pricePerNight: 3300,
    name: {
      en: "Sea Front Bungalow",
      he: "בקתה מול הים",
      es: "Bungalow Frente al Mar",
      fr: "Bungalow Front de Mer",
    },
    blurb: {
      en: "Our bungalow closest to the water: sea, garden and pool views, a double bed, and a terrace made for sunsets. Fridge, desk and wardrobe inside.",
      he: "הבקתה הקרובה ביותר שלנו למים: נוף לים, לגינה ולבריכה, מיטה זוגית ומרפסת שנבנתה לשקיעות. בפנים מקרר, שולחן עבודה וארון.",
      es: "Nuestro bungalow más cercano al agua: vistas al mar, al jardín y a la piscina, cama doble y una terraza hecha para los atardeceres. Nevera, escritorio y armario dentro.",
      fr: "Notre bungalow le plus proche de l'eau : vue mer, jardin et piscine, lit double et une terrasse faite pour les couchers de soleil. Réfrigérateur, bureau et armoire à l'intérieur.",
    },
  },
  {
    // 4 units.
    slug: "family-room",
    order: 12,
    images: [
      "siam-hotel-koh-tao-family-room",
      "siam-hotel-koh-tao-family-room-2",
      "siam-hotel-koh-tao-family-room-3",
      "siam-hotel-koh-tao-family-room-4",
      "siam-hotel-koh-tao-family-room-5",
      "siam-hotel-koh-tao-family-room-6",
      "siam-hotel-koh-tao-family-room-7",
      "siam-hotel-koh-tao-family-room-8",
    ],
    sleeps: 4,
    amenities: ["seaView", "poolView", "terrace", "ac", "fan", "hotWater", "ensuite", "tv", "safe", "fridge", "desk", "kettle", "wardrobe", "wifi", "poolAccess"],
    pricePerNight: 3300,
    soldOut: true,
    name: {
      en: "Family Room",
      he: "חדר משפחתי",
      es: "Habitación Familiar",
      fr: "Chambre Familiale",
    },
    blurb: {
      en: "One double bed and two singles for a family of four, with sea and pool views and a terrace. TV, safe, fridge, kettle, desk and wardrobe all inside.",
      he: "מיטה זוגית ושתי מיטות יחיד למשפחה של ארבעה, עם נוף לים ולבריכה ומרפסת. טלוויזיה, כספת, מקרר, קומקום, שולחן וארון - הכל בפנים.",
      es: "Una cama doble y dos individuales para una familia de cuatro, con vistas al mar y a la piscina y una terraza. TV, caja fuerte, nevera, hervidor, escritorio y armario incluidos.",
      fr: "Un lit double et deux lits simples pour une famille de quatre, avec vue mer et piscine et une terrasse. TV, coffre-fort, réfrigérateur, bouilloire, bureau et armoire à l'intérieur.",
    },
  },
];

/** Cheapest tier first. Rooms with a real price sort by it; the rest keep `order`. */
export const sortedRooms = () =>
  [...HOTEL_ROOMS].sort((a, b) => {
    if (a.pricePerNight != null && b.pricePerNight != null && a.pricePerNight !== b.pricePerNight) {
      return a.pricePerNight - b.pricePerNight;
    }
    return a.order - b.order;
  });

// ---------------------------------------------------------------------------
// Copy
// ---------------------------------------------------------------------------

export interface HotelCopy {
  seoTitle: string;
  seoDescription: string;
  breadcrumb: string;
  navRooms: string;
  navGallery: string;
  navFind: string;
  heroKicker: string;
  heroTitle: string;
  heroSubtitle: string;
  heroCta: string;
  heroWhatsapp: string;
  perks: string[];
  roomsTitle: string;
  roomsSubtitle: string;
  priceFrom: string;
  perNight: string;
  /** Price suffix for priceUnit "bed" rooms (the dorm). */
  perBed: string;
  priceOnRequest: string;
  sleeps: (n: number) => string;
  book: string;
  /** Badge + CTA replacement for `soldOut` rooms. */
  fullyBooked: string;
  /** Booking request form (BookingRequestForm.tsx). */
  requestToBook: string;
  orWhatsApp: string;
  bookCheckIn: string;
  bookCheckOut: string;
  bookGuests: string;
  bookName: string;
  bookEmail: string;
  bookPhone: string;
  bookNotes: string;
  bookSubmit: string;
  bookSending: string;
  bookSuccessTitle: string;
  /** Never carries the reference - the panel shows it as its own chip. */
  bookSuccessBody: string;
  /** Label above the reference chip (success panel, /hotel/book, emails). */
  bookRefLabel: string;
  bookError: string;
  bookClose: string;
  photosSoon: string;
  amenities: Record<AmenityKey, string>;
  goodToKnowTitle: string;
  goodToKnowItems: string[];
  galleryTitle: string;
  gallerySubtitle: string;
  galleryClose: string;
  galleryPrev: string;
  galleryNext: string;
  diveTitle: string;
  diveBody: string;
  diveCta: string;
  findTitle: string;
  findBody: string;
  findCta: string;
  contactTitle: string;
  contactBody: string;
  footerTagline: string;
  footerDiveLink: string;
  detailsSoon: string;
}

const AMENITIES_EN: Record<AmenityKey, string> = {
  ac: "Air conditioning",
  fan: "Ceiling fan",
  hotWater: "Hot water",
  ensuite: "Private bathroom",
  tv: "TV",
  safe: "In-room safe",
  fridge: "Fridge",
  kettle: "Kettle",
  wifi: "Free Wi-Fi",
  poolAccess: "Pool access",
  doubleBed: "Double bed",
  doubleOrTwin: "Double or twin beds",
  bunkBeds: "Bunk beds",
  lockers: "Lockers",
  wardrobe: "Wardrobe",
  desk: "Work desk",
  terrace: "Terrace",
  seatingArea: "Outdoor seating",
  seaView: "Sea view",
  poolView: "Pool view",
  gardenView: "Garden view",
  streetSide: "On the main street",
};

export const HOTEL_COPY: Record<Language, HotelCopy> = {
  en: {
    seoTitle: "Siam Hotel & Hostel - Rooms & Dorms on Sairee Beach, Koh Tao",
    seoDescription:
      "Rooms, dorm beds and a palm-garden pool on Sairee Beach, Koh Tao. Air-conditioned private rooms and budget dorms, steps from the sea - book direct on WhatsApp.",
    breadcrumb: "Hotel",
    navRooms: "Rooms",
    navGallery: "Gallery",
    navFind: "Find us",
    heroKicker: "Sairee Beach · Koh Tao",
    heroTitle: "Sleep where you dive",
    heroSubtitle:
      "Private rooms and dorm beds around a palm-garden pool, a short walk from the sea.",
    heroCta: "See rooms",
    heroWhatsapp: "Book on WhatsApp",
    perks: ["Swimming pool", "Restaurant & bar", "Spa & salon", "Siam Scuba dive center", "Mini-mart", "Free Wi-Fi"],
    roomsTitle: "Rooms",
    roomsSubtitle: "Pick a room, tap book. We answer on WhatsApp.",
    priceFrom: "From",
    perNight: "/ night",
    perBed: "/ bed / night",
    priceOnRequest: "Price on request",
    sleeps: (n) => `Sleeps ${n}`,
    book: "Book",
    fullyBooked: "Fully booked",
    requestToBook: "Request to book",
    orWhatsApp: "or chat on WhatsApp",
    bookCheckIn: "Check-in",
    bookCheckOut: "Check-out",
    bookGuests: "Guests",
    bookName: "Full name",
    bookEmail: "Email",
    bookPhone: "Phone (optional)",
    bookNotes: "Anything we should know? (optional)",
    bookSubmit: "Send request",
    bookSending: "Sending...",
    bookSuccessTitle: "Request sent!",
    bookSuccessBody:
      "Check your email - we sent you a confirmation of your request. We check availability personally, so your final answer usually arrives within a few hours.",
    bookRefLabel: "Your reference",
    bookError: "Something went wrong - please try again, or message us on WhatsApp.",
    bookClose: "Close",
    photosSoon: "Photos coming soon",
    amenities: AMENITIES_EN,
    goodToKnowTitle: "Good to know",
    goodToKnowItems: [
      "No free cancellation - cancellations are charged in full",
      "No breakfast service",
      "Payment at reception: cash, or card with a 3.5% fee",
      "3,000 THB deposit at check-in",
      "Extra bed 500 THB in some room types, subject to availability - ask in advance",
      "Free pier pickup",
      "Free motorbike parking",
      "Reception open until 21:00",
    ],
    galleryTitle: "The place",
    gallerySubtitle: "Pool, garden and the beach at the end of the road.",
    galleryClose: "Close",
    galleryPrev: "Previous",
    galleryNext: "Next",
    diveTitle: "Diving with Siam Scuba",
    diveBody:
      "We are the hotel of a PADI 5-star dive centre. Stay with us and dive with our instructors - courses, fun dives and daily boats on Koh Tao.",
    diveCta: "Go to Siam Scuba",
    findTitle: "Find us",
    findBody: "Sairee Beach, Koh Tao, Thailand.",
    findCta: "Open in Maps",
    contactTitle: "Questions?",
    contactBody: "Message us on WhatsApp - we usually reply within the hour.",
    footerTagline: "Rooms, dorms and a pool on Sairee Beach, Koh Tao.",
    footerDiveLink: "Siam Scuba diving",
    detailsSoon: "Details coming soon",
  },

  he: {
    seoTitle: "סיאם מלון והוסטל - חדרים ומיטות בחוף סיירי, קוטאו",
    seoDescription:
      "חדרים, מיטות בחדר משותף ובריכה בגינת דקלים על חוף סיירי בקוטאו. חדרים פרטיים ממוזגים והוסטל בתקציב נמוך, דקות הליכה מהים - הזמנה ישירה בוואטסאפ.",
    breadcrumb: "מלון",
    navRooms: "חדרים",
    navGallery: "גלריה",
    navFind: "איך מגיעים",
    heroKicker: "חוף סיירי · קוטאו",
    heroTitle: "לישון במקום שבו צוללים",
    heroSubtitle: "חדרים פרטיים ומיטות בחדר משותף סביב בריכה בגינת דקלים, הליכה קצרה מהים.",
    heroCta: "לחדרים",
    heroWhatsapp: "הזמנה בוואטסאפ",
    perks: ["בריכת שחייה", "מסעדה ובר", "ספא וסלון יופי", "מרכז הצלילה סיאם סקובה", "מיני-מרקט", "Wi-Fi חופשי"],
    roomsTitle: "החדרים",
    roomsSubtitle: "בוחרים חדר, לוחצים להזמנה. עונים בוואטסאפ.",
    priceFrom: "החל מ-",
    perNight: "/ לילה",
    perBed: "/ מיטה / לילה",
    priceOnRequest: "מחיר לפי בקשה",
    sleeps: (n) => `עד ${n} אורחים`,
    book: "להזמנה",
    fullyBooked: "מלא - אין זמינות",
    requestToBook: "בקשת הזמנה",
    orWhatsApp: "או שיחה בוואטסאפ",
    bookCheckIn: "צ'ק-אין",
    bookCheckOut: "צ'ק-אאוט",
    bookGuests: "אורחים",
    bookName: "שם מלא",
    bookEmail: "אימייל",
    bookPhone: "טלפון (לא חובה)",
    bookNotes: "משהו שכדאי שנדע? (לא חובה)",
    bookSubmit: "שליחת בקשה",
    bookSending: "שולח...",
    bookSuccessTitle: "הבקשה נשלחה!",
    bookSuccessBody:
      "בדקו את המייל - שלחנו אישור על קבלת הבקשה. אנחנו בודקים זמינות באופן אישי, כך שתשובה סופית מגיעה בדרך כלל תוך כמה שעות.",
    bookRefLabel: "מספר הבקשה שלך",
    bookError: "משהו השתבש - נסו שוב, או כתבו לנו בוואטסאפ.",
    bookClose: "סגירה",
    photosSoon: "תמונות בקרוב",
    amenities: {
      ac: "מיזוג אוויר",
      fan: "מאוורר תקרה",
      hotWater: "מים חמים",
      ensuite: "מקלחת פרטית",
      tv: "טלוויזיה",
      safe: "כספת",
      fridge: "מקרר",
      kettle: "קומקום",
      wifi: "Wi-Fi חופשי",
      poolAccess: "גישה לבריכה",
      doubleBed: "מיטה זוגית",
      doubleOrTwin: "מיטה זוגית או שתי מיטות",
      bunkBeds: "מיטות קומתיים",
      lockers: "לוקרים",
      wardrobe: "ארון בגדים",
      desk: "שולחן עבודה",
      terrace: "מרפסת",
      seatingArea: "פינת ישיבה חיצונית",
      seaView: "נוף לים",
      poolView: "נוף לבריכה",
      gardenView: "נוף לגינה",
      streetSide: "פונה לרחוב הראשי",
    },
    goodToKnowTitle: "טוב לדעת",
    goodToKnowItems: [
      "אין ביטול חינם - ביטול הזמנה מחויב במלואו",
      "אין שירות ארוחת בוקר",
      "תשלום בקבלה: מזומן, או כרטיס אשראי בתוספת 3.5%",
      "פיקדון של 3,000 באט בצ'ק-אין",
      "מיטה נוספת ב-500 באט בחלק מסוגי החדרים, בכפוף לזמינות - יש לתאם מראש",
      "איסוף חינם מהמזח",
      "חניית אופנועים חינם",
      "הקבלה פתוחה עד 21:00",
    ],
    galleryTitle: "המקום",
    gallerySubtitle: "בריכה, גינה והחוף בסוף הרחוב.",
    galleryClose: "סגירה",
    galleryPrev: "הקודם",
    galleryNext: "הבא",
    diveTitle: "צוללים עם סיאם סקובה",
    diveBody:
      "אנחנו המלון של מרכז צלילה PADI 5 כוכבים. ישנים אצלנו וצוללים עם המדריכים שלנו - קורסים, צלילות כיף וסירות יומיות בקוטאו.",
    diveCta: "לאתר סיאם סקובה",
    findTitle: "איך מגיעים",
    findBody: "חוף סיירי, קוטאו, תאילנד.",
    findCta: "פתיחה במפות",
    contactTitle: "שאלות?",
    contactBody: "כתבו לנו בוואטסאפ - בדרך כלל עונים תוך שעה.",
    footerTagline: "חדרים, הוסטל ובריכה על חוף סיירי בקוטאו.",
    footerDiveLink: "צלילה עם סיאם סקובה",
    detailsSoon: "פרטים בקרוב",
  },

  es: {
    seoTitle: "Siam Hotel & Hostel - Habitaciones y Dormitorios en Sairee Beach, Koh Tao",
    seoDescription:
      "Habitaciones, camas en dormitorio y piscina entre palmeras en Sairee Beach, Koh Tao. Habitaciones privadas con aire acondicionado y dormitorios económicos, a pasos del mar - reserva directa por WhatsApp.",
    breadcrumb: "Hotel",
    navRooms: "Habitaciones",
    navGallery: "Galería",
    navFind: "Cómo llegar",
    heroKicker: "Sairee Beach · Koh Tao",
    heroTitle: "Duerme donde buceas",
    heroSubtitle:
      "Habitaciones privadas y camas en dormitorio alrededor de una piscina entre palmeras, a un paseo del mar.",
    heroCta: "Ver habitaciones",
    heroWhatsapp: "Reservar por WhatsApp",
    perks: ["Piscina", "Restaurante y bar", "Spa y salón de belleza", "Centro de buceo Siam Scuba", "Minimercado", "Wi-Fi gratis"],
    roomsTitle: "Habitaciones",
    roomsSubtitle: "Elige habitación y pulsa reservar. Respondemos por WhatsApp.",
    priceFrom: "Desde",
    perNight: "/ noche",
    perBed: "/ cama / noche",
    priceOnRequest: "Precio a consultar",
    sleeps: (n) => `Para ${n} personas`,
    book: "Reservar",
    fullyBooked: "Completo",
    requestToBook: "Solicitar reserva",
    orWhatsApp: "o chatea por WhatsApp",
    bookCheckIn: "Check-in",
    bookCheckOut: "Check-out",
    bookGuests: "Huéspedes",
    bookName: "Nombre completo",
    bookEmail: "Email",
    bookPhone: "Teléfono (opcional)",
    bookNotes: "¿Algo que debamos saber? (opcional)",
    bookSubmit: "Enviar solicitud",
    bookSending: "Enviando...",
    bookSuccessTitle: "¡Solicitud enviada!",
    bookSuccessBody:
      "Revisa tu correo: te enviamos la confirmación de tu solicitud. Comprobamos la disponibilidad personalmente, así que la respuesta final suele llegar en unas horas.",
    bookRefLabel: "Tu referencia",
    bookError: "Algo salió mal - inténtalo de nuevo o escríbenos por WhatsApp.",
    bookClose: "Cerrar",
    photosSoon: "Fotos muy pronto",
    amenities: {
      ac: "Aire acondicionado",
      fan: "Ventilador de techo",
      hotWater: "Agua caliente",
      ensuite: "Baño privado",
      tv: "TV",
      safe: "Caja fuerte",
      fridge: "Nevera",
      kettle: "Hervidor",
      wifi: "Wi-Fi gratis",
      poolAccess: "Acceso a la piscina",
      doubleBed: "Cama doble",
      doubleOrTwin: "Cama doble o dos camas",
      bunkBeds: "Literas",
      lockers: "Taquillas",
      wardrobe: "Armario",
      desk: "Escritorio",
      terrace: "Terraza",
      seatingArea: "Zona de estar exterior",
      seaView: "Vista al mar",
      poolView: "Vista a la piscina",
      gardenView: "Vista al jardín",
      streetSide: "Da a la calle principal",
    },
    goodToKnowTitle: "A tener en cuenta",
    goodToKnowItems: [
      "Sin cancelación gratuita: las cancelaciones se cobran íntegramente",
      "Sin servicio de desayuno",
      "Pago en recepción: efectivo, o tarjeta con un 3,5% de recargo",
      "Depósito de 3.000 THB al hacer el check-in",
      "Cama extra por 500 THB en algunos tipos de habitación, según disponibilidad - consúltanos con antelación",
      "Recogida gratuita en el muelle",
      "Aparcamiento gratuito para motos",
      "Recepción abierta hasta las 21:00",
    ],
    galleryTitle: "El lugar",
    gallerySubtitle: "Piscina, jardín y la playa al final de la calle.",
    galleryClose: "Cerrar",
    galleryPrev: "Anterior",
    galleryNext: "Siguiente",
    diveTitle: "Bucea con Siam Scuba",
    diveBody:
      "Somos el hotel de un centro de buceo PADI 5 estrellas. Alójate con nosotros y bucea con nuestros instructores: cursos, inmersiones y barcos diarios en Koh Tao.",
    diveCta: "Ir a Siam Scuba",
    findTitle: "Cómo llegar",
    findBody: "Sairee Beach, Koh Tao, Tailandia.",
    findCta: "Abrir en Maps",
    contactTitle: "¿Dudas?",
    contactBody: "Escríbenos por WhatsApp: solemos responder en menos de una hora.",
    footerTagline: "Habitaciones, dormitorios y piscina en Sairee Beach, Koh Tao.",
    footerDiveLink: "Buceo con Siam Scuba",
    detailsSoon: "Detalles muy pronto",
  },

  fr: {
    seoTitle: "Siam Hotel & Hostel - Chambres et Dortoirs à Sairee Beach, Koh Tao",
    seoDescription:
      "Chambres, lits en dortoir et piscine dans un jardin de palmiers à Sairee Beach, Koh Tao. Chambres privées climatisées et dortoirs économiques, à deux pas de la mer - réservation directe sur WhatsApp.",
    breadcrumb: "Hôtel",
    navRooms: "Chambres",
    navGallery: "Galerie",
    navFind: "Nous trouver",
    heroKicker: "Sairee Beach · Koh Tao",
    heroTitle: "Dormez là où vous plongez",
    heroSubtitle:
      "Chambres privées et lits en dortoir autour d'une piscine dans un jardin de palmiers, à quelques pas de la mer.",
    heroCta: "Voir les chambres",
    heroWhatsapp: "Réserver sur WhatsApp",
    perks: ["Piscine", "Restaurant et bar", "Spa et salon de beauté", "Centre de plongée Siam Scuba", "Supérette", "Wi-Fi gratuit"],
    roomsTitle: "Chambres",
    roomsSubtitle: "Choisissez une chambre, appuyez sur réserver. On répond sur WhatsApp.",
    priceFrom: "À partir de",
    perNight: "/ nuit",
    perBed: "/ lit / nuit",
    priceOnRequest: "Prix sur demande",
    sleeps: (n) => `Pour ${n} personnes`,
    book: "Réserver",
    fullyBooked: "Complet",
    requestToBook: "Demander à réserver",
    orWhatsApp: "ou discuter sur WhatsApp",
    bookCheckIn: "Check-in",
    bookCheckOut: "Check-out",
    bookGuests: "Personnes",
    bookName: "Nom complet",
    bookEmail: "Email",
    bookPhone: "Téléphone (facultatif)",
    bookNotes: "Quelque chose à nous signaler ? (facultatif)",
    bookSubmit: "Envoyer la demande",
    bookSending: "Envoi...",
    bookSuccessTitle: "Demande envoyée !",
    bookSuccessBody:
      "Vérifiez votre boîte mail - nous vous avons envoyé une confirmation de votre demande. Nous vérifions la disponibilité personnellement ; la réponse définitive arrive généralement en quelques heures.",
    bookRefLabel: "Votre référence",
    bookError: "Un problème est survenu - réessayez, ou écrivez-nous sur WhatsApp.",
    bookClose: "Fermer",
    photosSoon: "Photos bientôt",
    amenities: {
      ac: "Climatisation",
      fan: "Ventilateur de plafond",
      hotWater: "Eau chaude",
      ensuite: "Salle de bain privée",
      tv: "TV",
      safe: "Coffre-fort",
      fridge: "Réfrigérateur",
      kettle: "Bouilloire",
      wifi: "Wi-Fi gratuit",
      poolAccess: "Accès à la piscine",
      doubleBed: "Lit double",
      doubleOrTwin: "Lit double ou lits jumeaux",
      bunkBeds: "Lits superposés",
      lockers: "Casiers",
      wardrobe: "Armoire",
      desk: "Bureau",
      terrace: "Terrasse",
      seatingArea: "Coin salon extérieur",
      seaView: "Vue sur la mer",
      poolView: "Vue sur la piscine",
      gardenView: "Vue sur le jardin",
      streetSide: "Côté rue principale",
    },
    goodToKnowTitle: "Bon à savoir",
    goodToKnowItems: [
      "Pas d'annulation gratuite - toute annulation est facturée en totalité",
      "Pas de service de petit-déjeuner",
      "Paiement à la réception : en espèces, ou par carte avec 3,5 % de frais",
      "Caution de 3 000 THB à l'arrivée",
      "Lit supplémentaire à 500 THB dans certaines chambres, selon disponibilité - à demander à l'avance",
      "Transfert gratuit depuis le port",
      "Parking moto gratuit",
      "Réception ouverte jusqu'à 21h00",
    ],
    galleryTitle: "Le lieu",
    gallerySubtitle: "La piscine, le jardin et la plage au bout de la rue.",
    galleryClose: "Fermer",
    galleryPrev: "Précédent",
    galleryNext: "Suivant",
    diveTitle: "Plongez avec Siam Scuba",
    diveBody:
      "Nous sommes l'hôtel d'un centre de plongée PADI 5 étoiles. Dormez chez nous et plongez avec nos instructeurs : cours, plongées loisir et bateaux quotidiens à Koh Tao.",
    diveCta: "Aller sur Siam Scuba",
    findTitle: "Nous trouver",
    findBody: "Sairee Beach, Koh Tao, Thaïlande.",
    findCta: "Ouvrir dans Maps",
    contactTitle: "Des questions ?",
    contactBody: "Écrivez-nous sur WhatsApp - nous répondons généralement dans l'heure.",
    footerTagline: "Chambres, dortoirs et piscine à Sairee Beach, Koh Tao.",
    footerDiveLink: "Plongée avec Siam Scuba",
    detailsSoon: "Détails bientôt",
  },
};

// ---------------------------------------------------------------------------
// Gallery (non-room photos, in display order)
// ---------------------------------------------------------------------------

export interface GalleryPhoto {
  slug: string;
  alt: Record<Language, string>;
}

export const HOTEL_GALLERY: GalleryPhoto[] = [
  {
    slug: "siam-hotel-koh-tao-pool",
    alt: {
      en: "Swimming pool surrounded by palms at Siam Hotel & Hostel, Koh Tao",
      he: "בריכת השחייה מוקפת דקלים בסיאם מלון והוסטל, קוטאו",
      es: "Piscina rodeada de palmeras en Siam Hotel & Hostel, Koh Tao",
      fr: "Piscine entourée de palmiers au Siam Hotel & Hostel, Koh Tao",
    },
  },
  {
    slug: "siam-hotel-koh-tao-pool-bar",
    alt: {
      en: "Swim-up pool bar with green stools",
      he: "בר בריכה עם שרפרפים ירוקים",
      es: "Bar en la piscina con taburetes verdes",
      fr: "Bar de piscine avec tabourets verts",
    },
  },
  {
    slug: "siam-hotel-koh-tao-rooftop-terrace",
    alt: {
      en: "Rooftop sun terrace with sea view loungers",
      he: "מרפסת גג שטופת שמש עם מיטות שיזוף ונוף לים",
      es: "Terraza en la azotea con tumbonas y vistas al mar",
      fr: "Terrasse sur le toit avec transats et vue sur la mer",
    },
  },
  {
    slug: "siam-hotel-koh-tao-sairee-beach-palm",
    alt: {
      en: "Leaning palm and longtail boats on Sairee Beach, Koh Tao",
      he: "דקל נטוי וסירות לונגטייל בחוף סיירי, קוטאו",
      es: "Palmera inclinada y barcos longtail en Sairee Beach, Koh Tao",
      fr: "Palmier penché et bateaux longtail sur Sairee Beach, Koh Tao",
    },
  },
  {
    slug: "siam-hotel-koh-tao-beach-lounge",
    alt: {
      en: "Beach lounge with bean bags at golden hour",
      he: "פינת ישיבה על החוף עם פופים בשעת הזהב",
      es: "Zona chill en la playa con pufs a la hora dorada",
      fr: "Salon de plage avec poufs à l'heure dorée",
    },
  },
  {
    slug: "siam-hotel-koh-tao-beach-restaurant-view",
    alt: {
      en: "Beachfront restaurant table looking out to sea",
      he: "שולחן במסעדה שעל החוף עם מבט לים",
      es: "Mesa del restaurante frente al mar",
      fr: "Table du restaurant en bord de mer",
    },
  },
  {
    slug: "siam-hotel-koh-tao-thai-massage",
    alt: {
      en: "Thai massage room with mattresses and silk cushions",
      he: "חדר עיסוי תאילנדי עם מזרנים וכריות משי",
      es: "Sala de masaje tailandés con colchonetas y cojines de seda",
      fr: "Salle de massage thaï avec matelas et coussins en soie",
    },
  },
  {
    slug: "siam-hotel-koh-tao-sunset-longtail-boats",
    alt: {
      en: "Sunset over Sairee Beach with longtail boats",
      he: "שקיעה מעל חוף סיירי עם סירות לונגטייל",
      es: "Atardecer en Sairee Beach con barcos longtail",
      fr: "Coucher de soleil sur Sairee Beach avec des bateaux longtail",
    },
  },
];

// ---------------------------------------------------------------------------
// Links
// ---------------------------------------------------------------------------

const WA_MESSAGE: Record<Language, (room?: string) => string> = {
  en: (room) =>
    room
      ? `Hi Siam Hotel & Hostel! I'd like to book the ${room}. Do you have availability?`
      : "Hi Siam Hotel & Hostel! I'd like to ask about a room in Koh Tao.",
  he: (room) =>
    room
      ? `היי סיאם מלון והוסטל! אשמח להזמין ${room}. יש זמינות?`
      : "היי סיאם מלון והוסטל! אשמח לקבל פרטים על חדר בקוטאו.",
  es: (room) =>
    room
      ? `¡Hola Siam Hotel & Hostel! Me gustaría reservar la ${room}. ¿Tienen disponibilidad?`
      : "¡Hola Siam Hotel & Hostel! Quisiera información sobre una habitación en Koh Tao.",
  fr: (room) =>
    room
      ? `Bonjour Siam Hotel & Hostel ! Je souhaite réserver la ${room}. Avez-vous des disponibilités ?`
      : "Bonjour Siam Hotel & Hostel ! Je voudrais des informations sur une chambre à Koh Tao.",
};

export function hotelWhatsAppLink(lang: Language, roomName?: string): string {
  const text = WA_MESSAGE[lang](roomName);
  return `https://wa.me/${HOTEL_WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`;
}

export const HOTEL_LANGS: Language[] = ["en", "he", "es", "fr"];

export const hotelPath = (lang: Language) => (lang === "en" ? "/hotel" : `/${lang}/hotel`);

export const hotelUrl = (lang: Language) => `https://siamscuba.com${hotelPath(lang)}`;

/**
 * Where the "back to the dive site" links point, per language.
 *
 * NOT `/${lang}`: there is no /fr route - "/" is the multilingual homepage and
 * doubles as the French destination (see LOCALE_FAMILIES in
 * src/lib/localeRoutes.ts). Hardcoding the prefix shipped a dead /fr link that
 * `bun run check:links` caught before it reached a preview.
 */
export const diveSiteHomePath = (lang: Language) =>
  lang === "he" ? "/he" : lang === "es" ? "/es" : "/";

/**
 * Reciprocal hreflang cluster for the four hotel URLs. Built here rather than
 * per page so a page cannot drift out of the cluster (Google drops the whole
 * annotation when it is not reciprocal - see src/lib/localeRoutes.ts).
 */
export const hotelHreflangAlternates = () =>
  Object.fromEntries(HOTEL_LANGS.map((l) => [l, hotelUrl(l)])) as Record<Language, string>;

/**
 * schema.org Hotel for the property. Fields we do not have yet (check-in/out
 * times) are omitted rather than guessed - they fill themselves in from
 * HOTEL_INFO the moment Ben confirms the real values. Note: priceRange's lower
 * bound is the dorm's per-bed price.
 */
export function buildHotelSchema(lang: Language) {
  const copy = HOTEL_COPY[lang];
  const prices = HOTEL_ROOMS.map((r) => r.pricePerNight).filter((p): p is number => p != null);

  return {
    "@context": "https://schema.org",
    "@type": "Hotel",
    name: HOTEL_INFO.name,
    description: copy.seoDescription,
    url: hotelUrl(lang),
    inLanguage: lang,
    image: [
      "https://siamscuba.com/hotel/siam-hotel-koh-tao-palm-sunset.webp",
      "https://siamscuba.com/hotel/siam-hotel-koh-tao-pool.webp",
      "https://siamscuba.com/hotel/siam-hotel-koh-tao-rooftop-terrace.webp",
    ],
    address: {
      "@type": "PostalAddress",
      addressLocality: "Koh Tao",
      addressRegion: "Surat Thani",
      addressCountry: "TH",
      ...(HOTEL_INFO.address ? { streetAddress: HOTEL_INFO.address } : {}),
    },
    ...(HOTEL_INFO.mapsUrl ? { hasMap: HOTEL_INFO.mapsUrl } : {}),
    amenityFeature: [
      { "@type": "LocationFeatureSpecification", name: "Swimming pool", value: true },
      { "@type": "LocationFeatureSpecification", name: "Free Wi-Fi", value: true },
      { "@type": "LocationFeatureSpecification", name: "Air conditioning", value: true },
    ],
    ...(HOTEL_INFO.checkIn ? { checkinTime: HOTEL_INFO.checkIn } : {}),
    ...(HOTEL_INFO.checkOut ? { checkoutTime: HOTEL_INFO.checkOut } : {}),
    ...(prices.length
      ? {
          priceRange: `฿${Math.min(...prices).toLocaleString()} - ฿${Math.max(...prices).toLocaleString()}`,
        }
      : {}),
    containedInPlace: { "@type": "Place", name: "Sairee Beach, Koh Tao" },
  };
}
